networks:
  default:
    name: platform
    external: true

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: mydatabase
    ports:
      - "10000:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: